apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- serviceaccount.yaml
- certificate.yaml

images:
- name: controller
  newName: rfinner/tbn-contour-authserver
  newTag: v0.1.5
- name: testserver
  newName: tbn-contour-authserver
  newTag: latest
