apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- serviceaccount.yaml
- certificate.yaml
- role.yaml
- rolebinding.yaml

images:
- name: controller
  newName: rfinner/contour-authserver
  newTag: "1.7"
- name: htpasswd
  newName: rfinner/contour-authserver
  newTag: "1.7"
